apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: nginx
    name: test-container
    volumeMounts:
    - mountPath: /bondi2/binary
      name: test-volume
      readOnly: true
  volumes:
  - name: test-volume
    hostPath:
      path: /bondi/binary # directory location on host
      type: File
